version: '3.9'
services:
  postgis:
    container_name: docker_postgis
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=green
      - POSTGRES_PASSWORD=green
      - POSTGRES_DB=green
    ports:
      - '5433:5432'
    volumes:
      - data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  pgadmin-data: